// Block Components Library
// These are wrapper components for the page builder

import HeroBlock from './HeroBlock';
import TextBlock from './TextBlock';
import ImageBlock from './ImageBlock';
import ButtonBlock from './ButtonBlock';
import CardBlock from './CardBlock';
import ContainerBlock from './ContainerBlock';
import SpacerBlock from './SpacerBlock';
import HeadingBlock from './HeadingBlock';
import AlertBlock from './AlertBlock';
import BadgeBlock from './BadgeBlock';
import DividerBlock from './DividerBlock';
import QuoteBlock from './QuoteBlock';
import ListBlock from './ListBlock';
import VideoBlock from './VideoBlock';
import MapBlock from './MapBlock';
import MarqueeBlock from './MarqueeBlock';
import StatsBlock from './StatsBlock';
import FeaturesBlock from './FeaturesBlock';
import TestimonialBlock from './TestimonialBlock';
import CTABlock from './CTABlock';
import GridBlock from './GridBlock';
import AccordionBlock from './AccordionBlock';
import TabsBlock from './TabsBlock';
import GalleryBlock from './GalleryBlock';
import CarouselBlock from './CarouselBlock';
import FormBlock from './FormBlock';
import ContentSectionBlock from './ContentSectionBlock';
import ColumnsBlock from './ColumnsBlock';
import PostsCardBlock from './PostsCardBlock';
import PartnersBlock from './PartnersBlock';
import EventsBlock from './EventsBlock';
import TestimonialsGridBlock from './TestimonialsGridBlock';
import NewsGridBlock from './NewsGridBlock';
// New blocks
import TeamBlock from './TeamBlock';
import TimelineBlock from './TimelineBlock';
import CountdownBlock from './CountdownBlock';
import TableBlock from './TableBlock';
import FileDownloadBlock from './FileDownloadBlock';
import EmbedBlock from './EmbedBlock';
import ContactInfoBlock from './ContactInfoBlock';
import PricingBlock from './PricingBlock';
import ProgressBlock from './ProgressBlock';
import ArticleCardBlock from './ArticleCardBlock';

// Block Registry - Maps block types to components
export const BLOCK_REGISTRY = {
  hero: HeroBlock,
  text: TextBlock,
  image: ImageBlock,
  button: ButtonBlock,
  card: CardBlock,
  container: ContainerBlock,
  spacer: SpacerBlock,
  heading: HeadingBlock,
  alert: AlertBlock,
  badge: BadgeBlock,
  divider: DividerBlock,
  quote: QuoteBlock,
  list: ListBlock,
  video: VideoBlock,
  map: MapBlock,
  marquee: MarqueeBlock,
  stats: StatsBlock,
  features: FeaturesBlock,
  testimonial: TestimonialBlock,
  cta: CTABlock,
  grid: GridBlock,
  accordion: AccordionBlock,
  tabs: TabsBlock,
  gallery: GalleryBlock,
  carousel: CarouselBlock,
  form: FormBlock,
  contentSection: ContentSectionBlock,
  columns: ColumnsBlock,
  postsCard: PostsCardBlock,
  partners: PartnersBlock,
  events: EventsBlock,
  testimonialsGrid: TestimonialsGridBlock,
  newsGrid: NewsGridBlock,
  // New blocks
  team: TeamBlock,
  timeline: TimelineBlock,
  countdown: CountdownBlock,
  table: TableBlock,
  fileDownload: FileDownloadBlock,
  embed: EmbedBlock,
  contactInfo: ContactInfoBlock,
  pricing: PricingBlock,
  progress: ProgressBlock,
  articleCard: ArticleCardBlock,
};

// Block Definitions - For the block picker UI
export const BLOCK_DEFINITIONS = [
  {
    type: 'heading',
    name: 'Heading',
    icon: '📝',
    category: 'Content',
    description: 'Add a heading (H1-H6)',
    defaultProps: {
      text: 'Your Heading Here',
      level: 2,
      align: 'left',
    },
  },
  {
    type: 'text',
    name: 'Text / Paragraph',
    icon: '📄',
    category: 'Content',
    description: 'Add rich text content',
    defaultProps: {
      content: '<p>Your text content here...</p>',
    },
  },
  {
    type: 'image',
    name: 'Image',
    icon: '🖼️',
    category: 'Media',
    description: 'Add an image',
    defaultProps: {
      src: '',
      alt: 'Image',
      caption: '',
      customWidth: '',
      alignment: 'center',
    },
  },
  {
    type: 'button',
    name: 'Button',
    icon: '🔘',
    category: 'Interactive',
    description: 'Add a call-to-action button',
    defaultProps: {
      text: 'Click Me',
      variant: 'primary',
      size: 'md',
      href: '#',
    },
  },
  {
    type: 'card',
    name: 'Card',
    icon: '🃏',
    category: 'Layout',
    description: 'Add a card container',
    defaultProps: {
      variant: 'default',
      padding: 'md',
      shadow: 'md',
    },
  },
  {
    type: 'container',
    name: 'Container',
    icon: '📦',
    category: 'Layout',
    description: 'Add a responsive container',
    defaultProps: {
      size: 'default',
      padding: true,
    },
  },
  {
    type: 'hero',
    name: 'Hero Section',
    icon: '🎭',
    category: 'Sections',
    description: 'Add a hero banner with gradient overlay',
    defaultProps: {
      title: 'Welcome',
      subtitle: 'Subtitle text',
      backgroundImage: '',
      height: 'lg',
      overlay: true,
      overlayStyle: 'gradient', // gradient, dark, light, blue, purple, none
      textAlign: 'center', // center, left, right
    },
  },
  {
    type: 'spacer',
    name: 'Spacer',
    icon: '↕️',
    category: 'Layout',
    description: 'Add vertical spacing',
    defaultProps: {
      height: 'md',
    },
  },
  {
    type: 'alert',
    name: 'Alert',
    icon: '⚠️',
    category: 'Content',
    description: 'Add an alert message',
    defaultProps: {
      type: 'info',
      title: 'Info',
      message: 'This is an alert message',
    },
  },
  {
    type: 'badge',
    name: 'Badge',
    icon: '🏷️',
    category: 'Content',
    description: 'Add a badge/label',
    defaultProps: {
      text: 'Badge',
      variant: 'primary',
      size: 'md',
    },
  },
  {
    type: 'divider',
    name: 'Divider',
    icon: '➖',
    category: 'Layout',
    description: 'Add a horizontal divider line',
    defaultProps: {
      style: 'solid',
      color: 'gray',
      thickness: '1',
      spacing: 'md',
    },
  },
  {
    type: 'quote',
    name: 'Quote',
    icon: '💬',
    category: 'Content',
    description: 'Add a blockquote with citation',
    defaultProps: {
      quote: 'Enter your quote here',
      author: '',
      role: '',
      variant: 'default',
      size: 'md',
    },
  },
  {
    type: 'list',
    name: 'List',
    icon: '📋',
    category: 'Content',
    description: 'Add bullet or numbered list',
    defaultProps: {
      items: ['Item 1', 'Item 2', 'Item 3'],
      type: 'bullet',
      icon: '•',
      spacing: 'normal',
    },
  },
  {
    type: 'video',
    name: 'Video',
    icon: '🎥',
    category: 'Media',
    description: 'Embed YouTube, Vimeo or direct video',
    defaultProps: {
      url: '',
      type: 'youtube',
      aspectRatio: '16/9',
      autoplay: false,
      controls: true,
      caption: '',
    },
  },
  {
    type: 'map',
    name: 'Map',
    icon: '🗺️',
    category: 'Media',
    description: 'Embed Google Maps location',
    defaultProps: {
      address: '',
      lat: '',
      lng: '',
      zoom: 15,
      height: '400px',
      caption: '',
    },
  },
  {
    type: 'marquee',
    name: 'Marquee',
    icon: '📜',
    category: 'Content',
    description: 'Add scrolling text banner',
    defaultProps: {
      text: 'Enter your scrolling text here',
      speed: 'normal',
      direction: 'left',
      bgColor: 'primary',
      textColor: 'white',
      pauseOnHover: true,
    },
  },
  {
    type: 'stats',
    name: 'Statistics',
    icon: '📊',
    category: 'Sections',
    description: 'Display statistics or metrics',
    defaultProps: {
      stats: [
        { value: '1000+', label: 'Siswa Aktif', icon: '👨‍🎓' },
        { value: '50+', label: 'Tenaga Pengajar', icon: '👨‍🏫' },
        { value: '15+', label: 'Program Keahlian', icon: '🎓' },
        { value: '25+', label: 'Tahun Berpengalaman', icon: '🏆' },
      ],
      columns: 4,
      variant: 'default',
      showIcons: true,
    },
  },
  {
    type: 'features',
    name: 'Features',
    icon: '✨',
    category: 'Sections',
    description: 'Display feature list with icons',
    defaultProps: {
      features: [
        { icon: '✨', title: 'Feature 1', description: 'Description for feature 1' },
        { icon: '🚀', title: 'Feature 2', description: 'Description for feature 2' },
        { icon: '💡', title: 'Feature 3', description: 'Description for feature 3' },
      ],
      columns: 3,
      layout: 'grid',
      iconSize: 'md',
    },
  },
  {
    type: 'testimonial',
    name: 'Testimonial',
    icon: '⭐',
    category: 'Sections',
    description: 'Display customer testimonial',
    defaultProps: {
      name: 'John Doe',
      role: 'CEO, Company',
      image: '',
      quote: 'This is an amazing testimonial quote.',
      rating: 5,
      variant: 'default',
    },
  },
  {
    type: 'cta',
    name: 'Call to Action',
    icon: '📢',
    category: 'Sections',
    description: 'Add CTA section with buttons',
    defaultProps: {
      title: 'Ready to Get Started?',
      description: 'Join us today and experience the difference.',
      buttonText: 'Get Started',
      buttonUrl: '#',
      secondaryButtonText: '',
      secondaryButtonUrl: '#',
      backgroundImage: '',
      backgroundColor: 'primary',
      textColor: 'white',
      layout: 'centered',
    },
  },
  {
    type: 'contentSection',
    name: 'Content Section',
    icon: '📰',
    category: 'Sections',
    description: 'Flexible content section with title, description, and buttons',
    defaultProps: {
      title: 'Cerita pengalaman menarik dan berkesan oleh alumni kami',
      subtitle: '',
      description: 'SMK Kristen 5 Klaten telah memiliki sertifikat ISO 9008:2015 dan menggandeng mitra industri guna menjamin mutu pendidikan dan keselarasan dengan industri.',
      buttonText: 'BAGIKAN CERITAMU',
      buttonUrl: '#',
      buttonVariant: 'outline',
      secondaryButtonText: '',
      secondaryButtonUrl: '#',
      backgroundImage: '',
      backgroundColor: 'dark',
      textAlign: 'left',
      padding: 'lg',
      variant: 'default',
      showDivider: false,
    },
  },
  {
    type: 'grid',
    name: 'Grid Layout',
    icon: '🔲',
    category: 'Layout',
    description: 'Multi-column grid layout',
    defaultProps: {
      columns: 2,
      gap: 'md',
    },
  },
  {
    type: 'columns',
    name: 'Columns Layout',
    icon: '📊',
    category: 'Layout',
    description: 'Flexible column layout with nested blocks (2:1, 1:2, 1:1:1, etc)',
    defaultProps: {
      layout: '2-1',
      gap: 'lg',
      verticalAlign: 'start',
      columns: [
        { blocks: [] },
        { blocks: [] },
      ],
      reverseOnMobile: false,
    },
  },
  {
    type: 'postsCard',
    name: 'Posts Card',
    icon: '📰',
    category: 'Dynamic',
    description: 'Display recent posts/articles from category (supports multi-select)',
    defaultProps: {
      title: 'POSTINGAN TERBARU',
      linkText: 'LIHAT LAINNYA',
      linkUrl: '/artikel',
      categories: [], // Array of { slug, name } for filtering
      category: '', // Legacy support
      jurusan: '',
      limit: 3,
      showDate: true,
      showExcerpt: true,
      variant: 'default',
      backgroundColor: 'white',
    },
  },
  {
    type: 'accordion',
    name: 'Accordion',
    icon: '📑',
    category: 'Interactive',
    description: 'Expandable accordion/FAQ',
    defaultProps: {
      items: [
        { title: 'Accordion Item 1', content: 'Content for item 1' },
        { title: 'Accordion Item 2', content: 'Content for item 2' },
        { title: 'Accordion Item 3', content: 'Content for item 3' },
      ],
      allowMultiple: false,
      variant: 'default',
    },
  },
  {
    type: 'tabs',
    name: 'Tabs',
    icon: '📑',
    category: 'Interactive',
    description: 'Tabbed content with nested blocks support',
    defaultProps: {
      tabs: [
        { label: 'Tab 1', content: '', blocks: [] },
        { label: 'Tab 2', content: '', blocks: [] },
        { label: 'Tab 3', content: '', blocks: [] },
      ],
      variant: 'default',
    },
  },
  {
    type: 'gallery',
    name: 'Image Gallery',
    icon: '🖼️',
    category: 'Media',
    description: 'Image gallery with lightbox',
    defaultProps: {
      images: [
        { src: 'https://via.placeholder.com/400', alt: 'Image 1', caption: '' },
        { src: 'https://via.placeholder.com/400', alt: 'Image 2', caption: '' },
        { src: 'https://via.placeholder.com/400', alt: 'Image 3', caption: '' },
      ],
      columns: 3,
      gap: 'md',
      rounded: true,
      lightbox: true,
    },
  },
  {
    type: 'carousel',
    name: 'Carousel',
    icon: '🎠',
    category: 'Media',
    description: 'Image carousel/slider',
    defaultProps: {
      slides: [
        { image: 'https://via.placeholder.com/800x400', title: 'Slide 1', description: 'Description 1' },
        { image: 'https://via.placeholder.com/800x400', title: 'Slide 2', description: 'Description 2' },
        { image: 'https://via.placeholder.com/800x400', title: 'Slide 3', description: 'Description 3' },
      ],
      autoplay: true,
      interval: 5000,
      showIndicators: true,
      showControls: true,
      height: '400px',
    },
  },
  {
    type: 'form',
    name: 'Contact Form',
    icon: '📧',
    category: 'Interactive',
    description: 'Contact form with fields',
    defaultProps: {
      title: 'Contact Us',
      description: 'Fill out the form below.',
      fields: [
        { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Your name' },
        { name: 'email', label: 'Email', type: 'email', required: true, placeholder: 'your@email.com' },
        { name: 'message', label: 'Message', type: 'textarea', required: true, placeholder: 'Your message' },
      ],
      submitButtonText: 'Send Message',
      successMessage: 'Thank you! Your message has been sent.',
      endpoint: '/api/contact',
    },
  },
  {
    type: 'partners',
    name: 'Partners / Logo Cloud',
    icon: '🤝',
    category: 'Dynamic',
    description: 'Display partner company logos from database',
    defaultProps: {
      title: 'ALUMNI KAMI TELAH BEKERJA DI TOP COMPANY',
      subtitle: '',
      columns: 3,
      gap: 'md',
      variant: 'default',
      showTitle: true,
      backgroundColor: 'white',
      logoHeight: 'md',
      fetchFromAPI: true,
      limit: 6,
    },
  },
  {
    type: 'events',
    name: 'Events / Agenda',
    icon: '📅',
    category: 'Dynamic',
    description: 'Display upcoming events with date cards and filters',
    defaultProps: {
      title: 'KEGIATAN SISWA DAN GURU',
      subtitle: 'AGENDA YANG AKAN HADIR, BAIK ACARA DI SEKOLAH ATAUPUN LUAR SEKOLAH',
      showFilters: true,
      filterOptions: ['Semua', 'Akademik', 'Non Akademik'],
      limit: 6,
      columns: 2,
      variant: 'default',
      backgroundColor: 'gradient',
      showViewAllButton: true,
      viewAllText: 'LIHAT SEMUA AGENDA',
      viewAllUrl: '/agenda',
      fetchFromAPI: true,
    },
  },
  {
    type: 'testimonialsGrid',
    name: 'Testimonials Grid',
    icon: '💬',
    category: 'Dynamic',
    description: 'Display multiple alumni testimonials in scrolling grid',
    defaultProps: {
      title: 'Cerita pengalaman menarik dan berkesan oleh alumni kami',
      description: 'SMK Kristen 5 Klaten telah memiliki sertifikat ISO 9008:2015 dan menggandeng mitra industri guna menjamin mutu pendidikan dan keselarasan dengan industri.',
      buttonText: 'BAGIKAN CERITAMU',
      buttonUrl: '#',
      columns: 2,
      limit: 6,
      variant: 'default',
      backgroundColor: 'dark',
      showAnimation: true,
      fetchFromAPI: true,
    },
  },
  {
    type: 'newsGrid',
    name: 'News Grid',
    icon: '📰',
    category: 'Dynamic',
    description: 'Display news/articles with featured layout and top list',
    defaultProps: {
      title: '',
      showFeatured: true,
      showTopList: true,
      topListTitle: 'TOP 5 BERITA',
      showBottomSection: true,
      bottomSectionTitle: 'BERITA UTAMA',
      limit: 6,
      category: '',
      jurusan: '',
      variant: 'default',
      backgroundColor: 'white',
      fetchFromAPI: true,
    },
  },
  // New blocks
  {
    type: 'team',
    name: 'Team / Staff',
    icon: '👥',
    category: 'Sections',
    description: 'Display team members or staff profiles with photos',
    defaultProps: {
      title: 'Tim Kami',
      subtitle: '',
      members: [
        { name: 'Nama Lengkap', role: 'Kepala Sekolah', image: '', bio: '', social: {} },
        { name: 'Nama Lengkap', role: 'Wakil Kepala Sekolah', image: '', bio: '', social: {} },
        { name: 'Nama Lengkap', role: 'Guru', image: '', bio: '', social: {} },
      ],
      columns: 3,
      variant: 'card',
      showBio: false,
      showSocial: true,
      backgroundColor: 'white',
    },
  },
  {
    type: 'timeline',
    name: 'Timeline',
    icon: '📅',
    category: 'Sections',
    description: 'Display school history or milestones in timeline format',
    defaultProps: {
      title: 'Sejarah Kami',
      subtitle: '',
      items: [
        { year: '1990', title: 'Pendirian Sekolah', description: 'SMK Kristen 5 Klaten didirikan', icon: '🏫' },
        { year: '2000', title: 'Akreditasi A', description: 'Mendapat akreditasi A dari BAN-SM', icon: '🏆' },
        { year: '2010', title: 'Pembangunan Gedung Baru', description: 'Perluasan fasilitas sekolah', icon: '🏗️' },
        { year: '2020', title: 'Sertifikasi ISO', description: 'Mendapat sertifikat ISO 9001:2015', icon: '📜' },
      ],
      variant: 'alternating',
      showIcons: true,
      lineColor: 'primary',
      backgroundColor: 'white',
    },
  },
  {
    type: 'countdown',
    name: 'Countdown',
    icon: '⏰',
    category: 'Interactive',
    description: 'Display countdown timer for events or deadlines',
    defaultProps: {
      title: 'Pendaftaran Dibuka',
      subtitle: 'Jangan lewatkan kesempatan mendaftar!',
      targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      expiredMessage: 'Waktu telah berakhir!',
      buttonText: 'Daftar Sekarang',
      buttonUrl: '/pendaftaran',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      variant: 'default',
      size: 'lg',
      backgroundColor: 'primary',
      backgroundImage: '',
    },
  },
  {
    type: 'table',
    name: 'Table',
    icon: '📊',
    category: 'Content',
    description: 'Display tabular data (schedules, fees, etc.)',
    defaultProps: {
      title: '',
      subtitle: '',
      headers: ['Kolom 1', 'Kolom 2', 'Kolom 3'],
      rows: [
        ['Data 1', 'Data 2', 'Data 3'],
        ['Data 4', 'Data 5', 'Data 6'],
        ['Data 7', 'Data 8', 'Data 9'],
      ],
      caption: '',
      striped: true,
      bordered: true,
      hoverable: true,
      compact: false,
      variant: 'default',
      responsive: true,
      headerAlign: 'left',
      cellAlign: 'left',
    },
  },
  {
    type: 'fileDownload',
    name: 'File Download',
    icon: '📥',
    category: 'Interactive',
    description: 'Display downloadable files and documents',
    defaultProps: {
      title: 'Download Dokumen',
      subtitle: '',
      files: [
        { name: 'Brosur Pendaftaran', url: '#', type: 'pdf', size: '2.5 MB', description: '' },
        { name: 'Formulir Pendaftaran', url: '#', type: 'pdf', size: '500 KB', description: '' },
        { name: 'Jadwal Pelajaran', url: '#', type: 'xlsx', size: '1.2 MB', description: '' },
      ],
      variant: 'list',
      columns: 2,
      showFileSize: true,
      showDescription: true,
      showIcon: true,
      backgroundColor: 'white',
    },
  },
  {
    type: 'embed',
    name: 'Embed',
    icon: '🔗',
    category: 'Media',
    description: 'Embed external content (Instagram, TikTok, Spotify, etc.)',
    defaultProps: {
      title: '',
      type: 'custom',
      url: '',
      embedCode: '',
      aspectRatio: '16/9',
      maxWidth: '600px',
      align: 'center',
      caption: '',
      backgroundColor: 'transparent',
    },
  },
  {
    type: 'contactInfo',
    name: 'Contact Info',
    icon: '📞',
    category: 'Sections',
    description: 'Display contact information cards',
    defaultProps: {
      title: 'Hubungi Kami',
      subtitle: '',
      items: [
        { type: 'phone', label: 'Telepon', value: '(0272) 123456', url: 'tel:0272123456' },
        { type: 'whatsapp', label: 'WhatsApp', value: '0812-3456-7890', url: 'https://wa.me/6281234567890' },
        { type: 'email', label: 'Email', value: 'info@smkkristen5.sch.id', url: 'mailto:info@smkkristen5.sch.id' },
        { type: 'location', label: 'Alamat', value: 'Jl. Opak, Metuk, Tegalyoso, Klaten', url: '' },
      ],
      variant: 'cards',
      columns: 2,
      showLabels: true,
      showIcons: true,
      iconSize: 'md',
      backgroundColor: 'white',
    },
  },
  {
    type: 'pricing',
    name: 'Pricing / Tuition',
    icon: '💰',
    category: 'Sections',
    description: 'Display pricing or tuition comparison',
    defaultProps: {
      title: 'Biaya Pendidikan',
      subtitle: 'Pilih program yang sesuai dengan kebutuhan Anda',
      plans: [
        {
          name: 'Program Reguler',
          price: 'Rp 5.000.000',
          period: '/tahun',
          description: 'Program pembelajaran standar',
          features: ['Pembelajaran di kelas', 'Praktik laboratorium', 'Ekstrakurikuler dasar'],
          buttonText: 'Daftar Sekarang',
          buttonUrl: '/pendaftaran',
          highlighted: false,
          badge: '',
        },
        {
          name: 'Program Unggulan',
          price: 'Rp 7.500.000',
          period: '/tahun',
          description: 'Program dengan fasilitas lengkap',
          features: ['Semua fitur Reguler', 'Sertifikasi industri', 'Magang di perusahaan', 'Tablet pembelajaran'],
          buttonText: 'Daftar Sekarang',
          buttonUrl: '/pendaftaran',
          highlighted: true,
          badge: 'Populer',
        },
      ],
      columns: 2,
      variant: 'cards',
      showFeatures: true,
      backgroundColor: 'gray',
    },
  },
  {
    type: 'progress',
    name: 'Progress / Stats',
    icon: '📈',
    category: 'Sections',
    description: 'Display progress bars or achievement statistics',
    defaultProps: {
      title: 'Pencapaian Kami',
      subtitle: '',
      items: [
        { label: 'Kelulusan', value: 100, max: 100, suffix: '%', color: 'primary' },
        { label: 'Siswa Bekerja', value: 85, max: 100, suffix: '%', color: 'green' },
        { label: 'Lanjut Kuliah', value: 45, max: 100, suffix: '%', color: 'blue' },
        { label: 'Kepuasan Orang Tua', value: 95, max: 100, suffix: '%', color: 'yellow' },
      ],
      variant: 'horizontal',
      showValue: true,
      showLabel: true,
      animated: true,
      size: 'md',
      backgroundColor: 'white',
      columns: 1,
    },
  },
  {
    type: 'articleCard',
    name: 'Article Card',
    icon: '🃏',
    category: 'Sections',
    description: 'Customizable article/content card with hide/show options for each row',
    defaultProps: {
      // Content
      image: '',
      imageAlt: 'Article image',
      tags: [
        { text: 'tkj', color: 'gray' },
        { text: 'berita terbaru', color: 'yellow' },
      ],
      date: 'Selasa, 24 July 2025',
      title: 'Cerita pengalaman menarik dan berkesan oleh alumni kami',
      description: 'SMK Kristen 5 Klaten telah memiliki sertifikat ISO 9008:2015 dan menggandeng mitra industri guna menjamin mutu pendidikan dan keselarasan dengan industri.',
      buttonText: 'BAGIKAN CERITAMU',
      buttonUrl: '#',
      // Visibility options
      showImage: true,
      showTags: true,
      showDate: true,
      showTitle: true,
      showDescription: true,
      showButton: true,
      // Styling
      mode: 'dark',
      buttonColor: 'yellow',
      buttonCustomColor: '#facc15',
      buttonVariant: 'solid',
      imageHeight: 'md',
      imageFit: 'cover',
      imageRounded: 'lg',
      titleSize: 'lg',
      maxWidth: 'sm',
      padding: 'md',
      align: 'left',
    },
  },
];

export default BLOCK_REGISTRY;
